name = "QuEST"
uuid = "2459ce63-a949-4045-b34d-4c0e485dd26d"
authors = ["dojt <dotheis.work@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
